### Get token
POST http://localhost:8080/authenticate
Content-Type: application/json

{
  "username": "javainuseWithRole",
  "password": "password"
}

> {% client.global.set("auth_token", response.body.token); %}

### Request with token -> 200 OK

GET http://localhost:8080/hello
Authorization: Bearer {{auth_token}}

### Request without token -> 401 Unauthorized

GET http://localhost:8080/hello



### Send POST request with json body
POST http://localhost:8080/employees
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "emp4",
  "designation": "hacker"
}




